name: CD Pipeline BugStore

on:
    workflow_run:
        workflows: ["CI Pipeline BugStore"]
        types:
            - completed
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            # Checkout
            - name: Checkout code
              uses: actions/checkout@v4

            # Login to Azure Container Registry
            - name: Login to ACR
              uses: docker/login-action@v3
              with:
                  registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
                  username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
                  password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

            # Build and push Docker image
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./src
                  file: ./src/BugStore.API/Dockerfile
                  push: true
                  tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/bugstore-api:${{ github.sha }}

            # Login to Azure
            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Deploy to Azure Container Apps
            - name: Deploy to Azure Container Apps
              uses: azure/CLI@v1
              with:
                  azcliversion: 2.30.0
                  inlineScript: |
                      az containerapp update \
                        --name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
                        --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                        --image ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/bugstore-api:${{ github.sha }} \
                        --set-env-vars "ConnectionStrings__PostgreSql=${{ secrets.DATABASE_URL }}"
